### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by redarrow-rus** [nanego/redmine_second_wiki#4]
Hi!

I have Redmine instance with a test project which have both usual Wiki and Documentation enabled. Also, I have a special role in Redmine which has rights to see Wiki but has no right for Documentation.

But when I login with this restricted role into Redmine and go to the wiki index page (f.e. http://redmine/projects/test-project/wiki/index), I see both Wiki and Documentation page list. I can follow all the links.

In addition, if I place the link to any Documentation page in Wiki, it works.

So, there is no real separate permissions for the Documentation. Am I right?
Is it possible to fix it?

**Comment by nanego** [comment]
Hello.
Documentation and Wiki tabs have their own permissions.
Maybe you were using an early version of the plugin.
Do you still experience this issue with the latest version?

**Comment by nanego** [comment]
I am closing this stale issue. 
Please don't hesitate to re-open it if you still experience the problem with the latest version of the plugin.
